title: "iam-role"
description: "customorgyesrole"
stage: "ALPHA"
includedPermissions:
- iam.roles.create
- iam.roles.delete
- iam.roles.get
- iam.roles.list
- iam.roles.undelete
- iam.roles.update
- iam.serviceAccounts.create
- iam.serviceAccounts.delete
- iam.serviceAccounts.get
- iam.serviceAccounts.getIamPolicy
- iam.serviceAccounts.list
- iam.serviceAccounts.setIamPolicy
- iam.serviceAccounts.update
- resourcemanager.organizations.get
- resourcemanager.organizations.getIamPolicy
- resourcemanager.organizations.setIamPolicy
- resourcemanager.folder *
- resourcemanager.projects.get
- resourcemanager.projects.getIamPolicy
- resourcemanager.projects.list
- automl.datasets.setIamPolicy
- automl.models.setIamPolicy
- bigquery.datasets.setIamPolicy
- bigtable.instances.setIamPolicy
- cloudkms.cryptoKeys.setIamPolicy
- cloudkms.keyRings.setIamPolicy
- cloudtasks.queues.setIamPolicy
- compute.disks.setIamPolicy
- compute.globalOperations.setIamPolicy
- compute.images.setIamPolicy
- compute.instances.setIamPolicy
- compute.licenses.setIamPolicy
- compute.maintenancePolicies.setIamPolicy
- compute.regionOperations.setIamPolicy
- compute.securityPolicies.setIamPolicy
- compute.snapshots.setIamPolicy
- compute.subnetworks.setIamPolicy
- compute.zoneOperations.setIamPolicy
- dataproc.clusters.setIamPolicy
- dataproc.jobs.setIamPolicy
- dataproc.operations.setIamPolicy
- dataproc.workflowTemplates.setIamPolicy
- deploymentmanager.deployments.setIamPolicy
- ml.jobs.setIamPolicy
- ml.models.setIamPolicy
- pubsub.snapshots.setIamPolicy
- pubsub.subscriptions.setIamPolicy
- pubsub.topics.setIamPolicy
- resourcemanager.projects.setIamPolicy
- servicemanagement.services.setIamPolicy
- source.repos.setIamPolicy
- storage.buckets.setIamPolicy
- storage.objects.setIamPolicy 


